###
POST localhost:8080/user
content-type:application/json

{
  "login": "login",
  "password": "password",
  "name": "Petr"
}

###
POST localhost:8080/user
content-type:application/json

{
  "login": "1",
  "password": "1",
  "name": "1"
}

###
POST localhost:8080/user
content-type:application/json

{
  "login": "3",
  "password": "3",
  "name": "3"
}

### get User by id
GET localhost:8080/user/2

### get User by incorrect id
GET localhost:8080/user/2

### get User by login and password
GET localhost:8080/user/search?login=login&password=password

### get User by incorrect login and password
GET localhost:8080/user/search?login=log&password=pass

### delete User by id
DELETE localhost:8080/user/3

### delete User by incorrect id
DELETE localhost:8080/user/4